### ISSUE TITLE
A Request

### ISSUE THREAD

**Issue by wzshw** [kaiboy05/fbm#1]
Hello, thank you very much for sharing! I noticed that you referred to the code implemented in a master's thesis, so could you share that thesis as well? I'd like to learn more about your code, and I'd appreciate it !

**Comment by kaiboy05** [comment]
Hi, here is the fbm website from Ton Dieker: http://www.columbia.edu/~ad3217/fbm.html

**Comment by wzshw** [comment]
Um, Okay. Thank you very much ！
